# Generated by Django 5.0.4 on 2024-06-02 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategoriacurso',
            name='categoria_curso',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='subcategoria_curso',
        ),
        migrations.RemoveField(
            model_name='plan_curso',
            name='curso',
        ),
        migrations.RemoveField(
            model_name='recursocurso',
            name='curso',
        ),
        migrations.RemoveField(
            model_name='modulocurso',
            name='curso',
        ),
        migrations.RemoveField(
            model_name='venta_curso',
            name='curso',
        ),
        migrations.RemoveField(
            model_name='inscripcion_curso',
            name='curso',
        ),
        migrations.RemoveField(
            model_name='inscripcion_curso',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='plan_curso',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='alumno',
        ),
        migrations.RemoveField(
            model_name='venta_curso',
            name='venta',
        ),
        migrations.RemoveField(
            model_name='venta_pago',
            name='venta',
        ),
        migrations.DeleteModel(
            name='CategoriaCurso',
        ),
        migrations.DeleteModel(
            name='SubCategoriaCurso',
        ),
        migrations.DeleteModel(
            name='RecursoCurso',
        ),
        migrations.DeleteModel(
            name='ModuloCurso',
        ),
        migrations.DeleteModel(
            name='Curso',
        ),
        migrations.DeleteModel(
            name='Inscripcion_Curso',
        ),
        migrations.DeleteModel(
            name='Plan_Curso',
        ),
        migrations.DeleteModel(
            name='Plan',
        ),
        migrations.DeleteModel(
            name='Venta_Curso',
        ),
        migrations.DeleteModel(
            name='Venta',
        ),
        migrations.DeleteModel(
            name='Venta_Pago',
        ),
    ]
