# Generated by Django 5.0.4 on 2024-06-02 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0005_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoriacurso',
            options={'verbose_name': 'Categoría de Curso', 'verbose_name_plural': 'Categorías de Cursos'},
        ),
        migrations.AlterModelOptions(
            name='curso',
            options={'verbose_name': 'Curso', 'verbose_name_plural': 'Cursos'},
        ),
        migrations.AlterModelOptions(
            name='inscripcioncurso',
            options={'verbose_name': 'Inscripción al Curso', 'verbose_name_plural': 'Inscripciones a Cursos'},
        ),
        migrations.AlterModelOptions(
            name='modulocurso',
            options={'verbose_name': 'Módulo del Curso', 'verbose_name_plural': 'Módulos del Curso'},
        ),
        migrations.AlterModelOptions(
            name='plan',
            options={'verbose_name': 'Plan', 'verbose_name_plural': 'Planes'},
        ),
        migrations.AlterModelOptions(
            name='plancurso',
            options={'verbose_name': 'Plan del Curso', 'verbose_name_plural': 'Planes de Cursos'},
        ),
        migrations.AlterModelOptions(
            name='recursocurso',
            options={'verbose_name': 'Recurso del Curso', 'verbose_name_plural': 'Recursos del Curso'},
        ),
        migrations.AlterModelOptions(
            name='registroslanding',
            options={'verbose_name': 'Registro en Landing', 'verbose_name_plural': 'Registros en Landing'},
        ),
        migrations.AlterModelOptions(
            name='subcategoriacurso',
            options={'verbose_name': 'Subcategoría de Curso', 'verbose_name_plural': 'Subcategorías de Cursos'},
        ),
        migrations.AlterModelOptions(
            name='venta',
            options={'verbose_name': 'Venta', 'verbose_name_plural': 'Ventas'},
        ),
        migrations.AlterModelOptions(
            name='ventacurso',
            options={'verbose_name': 'Venta del Curso', 'verbose_name_plural': 'Ventas de Cursos'},
        ),
        migrations.AlterModelOptions(
            name='ventapago',
            options={'verbose_name': 'Pago de Venta', 'verbose_name_plural': 'Pagos de Venta'},
        ),
        migrations.AlterField(
            model_name='curso',
            name='duracion',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
