# Generated by Django 5.0.4 on 2024-06-04 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0006_alter_categoriacurso_options_alter_curso_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='duracion',
            field=models.DurationField(),
        ),
    ]
