# Generated by Django 5.0.4 on 2024-06-04 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0008_alter_curso_duracion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='duracion',
            field=models.DurationField(),
        ),
    ]
