# Generated by Django 5.0.4 on 2024-06-07 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0009_alter_curso_duracion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='imagen',
            field=models.ImageField(upload_to='curso_img/'),
        ),
    ]
