# Generated by Django 5.0.4 on 2024-06-07 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0010_alter_curso_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriacurso',
            name='imagen',
            field=models.ImageField(null=True, upload_to='categoria_img/'),
        ),
    ]
