# Generated by Django 5.0.4 on 2024-06-07 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0011_categoriacurso_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategoriacurso',
            name='categoria_curso',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='subcategoria_curso',
        ),
        migrations.RemoveField(
            model_name='modulocurso',
            name='curso',
        ),
        migrations.RemoveField(
            model_name='plancurso',
            name='curso',
        ),
        migrations.RemoveField(
            model_name='ventacurso',
            name='curso',
        ),
        migrations.RemoveField(
            model_name='recursocurso',
            name='curso',
        ),
        migrations.RemoveField(
            model_name='inscripcioncurso',
            name='curso',
        ),
        migrations.RemoveField(
            model_name='inscripcioncurso',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='plancurso',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='plan',
        ),
        migrations.DeleteModel(
            name='RegistrosLanding',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='alumno',
        ),
        migrations.RemoveField(
            model_name='ventacurso',
            name='venta',
        ),
        migrations.RemoveField(
            model_name='ventapago',
            name='venta',
        ),
        migrations.DeleteModel(
            name='CategoriaCurso',
        ),
        migrations.DeleteModel(
            name='SubCategoriaCurso',
        ),
        migrations.DeleteModel(
            name='ModuloCurso',
        ),
        migrations.DeleteModel(
            name='RecursoCurso',
        ),
        migrations.DeleteModel(
            name='Curso',
        ),
        migrations.DeleteModel(
            name='InscripcionCurso',
        ),
        migrations.DeleteModel(
            name='PlanCurso',
        ),
        migrations.DeleteModel(
            name='Plan',
        ),
        migrations.DeleteModel(
            name='VentaCurso',
        ),
        migrations.DeleteModel(
            name='Venta',
        ),
        migrations.DeleteModel(
            name='VentaPago',
        ),
    ]
