# Generated by Django 5.0.4 on 2024-06-16 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0014_registrolanding'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegistroLanding',
        ),
    ]
