# Generated by Django 5.0.4 on 2024-06-16 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0016_registrolanding'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegistrosLanding',
        ),
        migrations.AlterModelOptions(
            name='registrolanding',
            options={'verbose_name': 'Registro en Landing', 'verbose_name_plural': 'Registros en Landing'},
        ),
    ]
