# Generated by Django 5.0.4 on 2024-06-17 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0018_modulocurso_descripcion_modulocurso_duracion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriacurso',
            name='imagen',
            field=models.ImageField(null=True, upload_to='categoria_img/'),
        ),
        migrations.AlterField(
            model_name='subcategoriacurso',
            name='imagen',
            field=models.ImageField(null=True, upload_to='subcategoria_img/'),
        ),
    ]
