# Generated by Django 5.0.4 on 2024-06-19 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0019_alter_categoriacurso_imagen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventapago',
            name='paypal_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
