# Generated by Django 5.0.4 on 2024-06-19 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0020_ventapago_paypal_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ventapago',
            name='paypal_id',
        ),
        migrations.AddField(
            model_name='venta',
            name='monto_venta',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='paypal_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
