# Generated by Django 5.0.3 on 2024-06-20 04:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0022_remove_venta_monto_venta_remove_venta_paypal_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='ventacurso',
            name='curso',
        ),
        migrations.RemoveField(
            model_name='ventacurso',
            name='precio',
        ),
        migrations.AddField(
            model_name='venta',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='ventacurso',
            name='plan_curso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cursos.plancurso'),
        ),
    ]
