# Generated by Django 5.0.4 on 2024-06-09 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_customuser_foto_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='genero',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
