# Generated by Django 5.0.4 on 2024-06-11 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_customuser_genero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='genero',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
