# Generated by Django 5.0.4 on 2024-06-16 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_customuser_genero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='celular',
            field=models.CharField(max_length=15),
        ),
    ]
