# Generated by Django 5.0.4 on 2024-06-17 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_customuser_celular'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='foto_perfil',
            field=models.ImageField(null=True, upload_to='foto_perfil/'),
        ),
    ]
